name: Build and deploy static site to Azure Web App - SaaSValuationCalculator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*
        working-directory: ./SaaSValuationCalculator

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: SaaSValuationCalculator/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: static-site

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SaaSValuationCalculator'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SAASVALUATIONCALCULATOR }}
          package: .
